# Replace with your Discord Application ID
application_id: "1412401548599758958"

# Activity type: 0 = Playing, 1 = Streaming, 2 = Listening, 3 = Watching
type: 3

# Activity Details
name: "SKRT7"
details: "Watching COOKIES"
state: "16.0m"

# Activity Images
largeImageKey: "1444022771993804891"
largeImageText: "estt"
smallImageKey: "1377845999464087653"
smallImageText: "COOKIES"

# Activity URL (optional, works only with certain types)
url: "https://www.twitch.tv/monkt_nadr36"

# Activity Buttons (optional)
buttons:
  - name: "Visit Website"
    url: "https://s.skrt7.workers.dev/"
  - name: "COOKIES"
    url: "https://www.instagram.com/skrt7_66?igsh=bWZzeHdhNDJtOGo2"
    
